### ISSUE TITLE
Error in nuklear.py and general install issue

### ISSUE THREAD

**Issue by zombient** [billsix/pyNuklear#1]
Hi there.

Issue 1:

nuklear.py does not import "sys", so the call to "sys.exit(1)" at line 34 is unsuccesful.

I manually added the line "import sys" as line 22.

Issue 2:

I have built the nuklear lib in "/contrib/nuklear" as per the instructions, but upon running the demo ("/demo/glfw_opengl3/pyNuklearGLFWOpenGL3.py"), nothing happens.

I then try running "/demo/overview.py", which returns "Nuklear shared library not found".

Then on to "nuklear.py" (the dependency for "overview.py"), which returns "Nuklear shared library not found" as well.

I assume I need to install "nuklearGLFWOpenGL2.so" and "nuklearGLFWOpenGL3.so" as shared libraries in the system (I'm using Arch Linux, btw), since nuklear.py does not seem to check the "/contrib/nuklear" directory?

Issue 3:

I don't understand the use of "builtins" to check for "NUKLEAR_PATH". How would "NUKLEAR_PATH" be included by importing "builtins"? Is the shared library supposed to be included by the Python interpreter via LD_LIBRARY_PATH (if installed in the path(s) pointed to by the environment variable), then I would assume that's nothing to do with the "builtins" module?

NOTE:

Just got started with github and nuklear/pyNuklear today, so bear with me if got something wrong. :-)

Thanks for bringing nuklear to Python,
--mike

**Comment by billsix** [comment]
Issue 1:
Should be fixed on master.  Thank you.
Issue 2:
Not sure why nothing happens when you run the demos.  I'd like feedback, does it halt?  What's the return code?  Anyway in master, I have explicitly made the demos executable, with associated shebang's, so try them out.  (I tested on Arch as well, and it works for me). 
nuklear.py and overview.py are not meant to be executed directly.  nuklear.py contains the python to c bindings, and is meant to be imported, such as by the demo applications.  overview.py is just like nuklear's, it is independent of the rendering backend.
You should not need to install the so's anywhere, the demos link to them in their natural directory.
3) I am a Python noob.  With that said, unlike nuklear's c implementation, in which the demos can be linked against the appropriate shared library for rendering, my nuklear.py needs to know the shared library against which it should be linked, but nuklear.py itself should not be dependent with a rendering backend.  But how does one python script pass parameters to a library?  From what I understand, builtins is the standard mechanism within python of parameterizing a library before importing.

Hope this helps.  Please let me know if you are still having issues.

**Comment by billsix** [comment]
To answer more directly to Issue 3, the demo applications initialize builtins.NUKLEAR_PATH before importing nuklear.py.
