### ISSUE TITLE
Missing ```__init__.py``` (?)

### ISSUE THREAD

**Issue by Lompik** [billsix/pyNuklear#2]
Hi

I've followed the instruction in the Readme. But trying to run the demo after making nuklear gave the following error:

```
Traceback (most recent call last):
  File "./demo/glfw_opengl3/pyNuklearGLFWOpenGL3.py", line 28, in <module>
    import glfw.glfw as glfw
ModuleNotFoundError: No module named 'glfw.glfw'; 'glfw' is not a package
```

which is expected as an ```__init__.py``` is required for python to treat the folder as package ( [pydoc](https://docs.python.org/3/tutorial/modules.html#packages) ). After creating an empty init file, it worked as expected. I have not submitted a pull request because I guess it's working out for other without the ```__init__.py``` file, but I am wondering why.

System specs: 
linux 
glfw 3.2.1
python 3.6.4
python-opengl 3.1.0

**Comment by billsix** [comment]
Thank you for your input.

I don't know what's happening for you, because I don't know how packaging is supposed to work in Python.  I thought that as long as the glfw folder was relative to a folder on the PYTHONPATH, that glfw would resolve correctly.

I have added the files as you requested https://github.com/billsix/pyNuklear/commit/23c0c89e2d2d803475b0d21edabf96cb4622ba77

Thanks again.

**Comment by Zephrym** [comment]
Your init py is blank and not needed. You should remove it from the git. Not having a __init__.py is fine. This is normally used like a .h file to initialize things if you want but is not needed

**Comment by billsix** [comment]
I'm trying to fix the build process to be in line with pip and virtualenv.
I have a branch called pipify towards that, although it's not currently
working, I think that I am close.  Any help in this endeavor, I will
appreciate.

Bill
